# GCC support can be specified at major, minor, or micro version
# (e.g. 8, 8.2 or 8.2.0).
# See https://hub.docker.com/r/library/gcc/ for all supported GCC
# tags from Docker Hub.
# See https://docs.docker.com/samples/library/gcc/ for more on how to use this image
FROM gcc:latest

RUN apt-get update && apt-get -y install cmake

# These commands copy your files into the specified directory in the image
# and set that as the working location
COPY . /usr/src/cfs
WORKDIR /usr/src/cfs

# This command compiles your app using GCC, adjust for your source code
RUN make SIMULATION=native prep
RUN make
RUN make install


WORKDIR /usr/src/cfs/build/exe/cpu1/
# This command runs your application, comment out this line to compile only
CMD ["./core-cpu1"]

LABEL Name=cfs Version=0.0.1
